version: '3'
services:
  postgres:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
  app:
#    image: shulpov/spring-boot-spots-app
    build: ./
    container_name: spots_app
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/spot_map'
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=12345
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - db
    ports:
      - '8080:8080'