# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build & test & push to dockerHUB
    runs-on: ubuntu-latest
    steps:
    - name: Copying project to runner
      uses: actions/checkout@v3 # копирует проект в runner
    - name: Set up JDK 17
      uses: actions/setup-java@v3 # конфигурирует Eclipse 17 JDK
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven
    - name: Build with Maven
      run: mvn -f ./ clean install

    - name: Build & push docker image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: shulpov/spring-boot-spots-app
        tags: latest
        registry: docker.io
        dockerfile: ./Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
  
  deploy:
    name: Pull from docker & run images
    runs-on: ubuntu-latest
    steps:
    - name: Docker image pulling from hub
      run: |
        docker login -u shulpov
        ${{ secrets.DOCKER_RW_TOKEN }}
        docker pull shulpov/spring-boot-spots-app
    - name: Docker running
      run: docker run shulpov/spring-boot-spots-app &


  


    